services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
        POSTGRES_USER: greenlight
        POSTGRES_PASSWORD: greenlight
        POSTGRES_DB: greenlight
    volumes:
      - db:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  db:
